name: chatbot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gemini: ^2.0.5
  hive_flutter: ^1.1.0
  file_picker: ^8.1.2
  http: ^1.2.2
  jumping_dot: ^0.0.6
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  glass_kit: ^3.0.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: assets/logo.png
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: assets/logo.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/logo.png
  linux:
    generate: true
    image_path: assets/logo.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
